version: '3.8'

services:
  # Serviço PHP/Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
      - "9005:9005"
    volumes:
      - ../biblioteca:/var/www/html/biblioteca
      - ../biblioteca/storage:/var/www/html/biblioteca/storage
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_START_WITH_REQUEST=yes
    depends_on:
      - db
    networks:
      - laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Serviço do banco PostgreSQL
  db:
    image: postgres:15
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
      POSTGRES_DB: laravel
    ports:
      - "5432:5432"
    networks:
      - laravel
    volumes:
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./postgresql/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

networks:
  laravel:

volumes:
  pgdata:
